<main>
    <span id="lightsaberComm" class="lightsaber"></span>
    <form method="POST" action="index.php?action=commentaire" id="formcom">
        <h4>Laissez nous votre avis :</h4>
        <label for="titre">Titre:</label>
        <input type="text" id="titre" name="titre" required="" autocomplete="off">
        
        <label for="nom">Nom :</label>
        <input type="text" id="nom" name="nom" required="" autocomplete="off">
        
        <label for="prenom">Prénom :</label>
        <input type="text" id="prenom" name="prenom" required="" autocomplete="off">
        
        <label for="commentaire">Commentaire :</label>
        <textarea id="commentaire" name="commentaire" rows="5" cols="50" required="" autocomplete="off"></textarea>
        
        <input type="submit" name="avis">
    </form>
</main>
