<main id="navette">
    <span id="lightsabership" class="lightsaber"></span>
    <section class="gridtransports">
        <article class="transports">
            <img src="https://damienguichous.sites.3wa.io/projet_starwars/ressources/images/cargostellaire.png">
            <section class="infotransports">
                <h4>Nom : <?= $Transports[0]['nom'] ?></h4>
                <p>Classe : <?= $Transports[0]['classe'] ?> </p>
                <p>Constructeur : <?= $Transports[0]['constructeur'] ?></p>
                <p>Taille : <?= $Transports[0]['taille'] ?></p>
                <p>Équipage : <?= $Transports[0]['equipage'] ?></p>
                <p>Passagers : <?= $Transports[0]['passager'] ?></p>
                <p>Affiliation : <?= $Transports[0]['affiliation'] ?></p>
                <p>Soute : <?= $Transports[0]['soute'] ?></p>
            </section>
        </article>
        <article class="transports">
            <img src="https://damienguichous.sites.3wa.io/projet_starwars/ressources/images/GR75MediumTransport.png">
            <section class="infotransports">
                <h4 id="cargogr75">Nom : <?= $Transports[1]['nom'] ?></h4>
                <p>Classe : <?= $Transports[1]['classe'] ?> </p>
                <p>Constructeur : <?= $Transports[1]['constructeur'] ?></p>
                <p>Taille : <?= $Transports[1]['taille'] ?></p>
                <p>Équipage : <?= $Transports[1]['equipage'] ?></p>
                <p>Passagers : <?= $Transports[1]['passager'] ?></p>
                <p>Affiliation : <?= $Transports[1]['affiliation'] ?></p>
                <p>Soute : <?= $Transports[1]['soute'] ?></p>
            </section>
        </article>
        <article class="transports">
            <img src="https://damienguichous.sites.3wa.io/projet_starwars/ressources/images/corvette90.png">
            <section class="infotransports">
                <h4>Nom : <?= $Transports[2]['nom'] ?></h4>
                <p>Classe : <?= $Transports[2]['classe'] ?> </p>
                <p>Constructeur : <?= $Transports[2]['constructeur'] ?></p>
                <p>Taille : <?= $Transports[2]['taille'] ?></p>
                <p>Équipage : <?= $Transports[2]['equipage'] ?></p>
                <p>Passagers : <?= $Transports[2]['passager'] ?></p>
                <p>Affiliation : <?= $Transports[2]['affiliation'] ?></p>
                <p>Soute : <?= $Transports[2]['soute'] ?></p>
            </section>
        </article>
        <article class="transports">
            <img src="https://damienguichous.sites.3wa.io/projet_starwars/ressources/images/Ghost2.png">
            <section class="infotransports">
                <h4>Nom : <?= $Transports[3]['nom'] ?></h4>
                <p>Classe : <?= $Transports[3]['classe'] ?> </p>
                <p>Constructeur : <?= $Transports[3]['constructeur'] ?></p>
                <p>Taille : <?= $Transports[3]['taille'] ?></p>
                <p>Équipage : <?= $Transports[3]['equipage'] ?></p>
                <p>Passagers : <?= $Transports[3]['passager'] ?></p>
                <p>Affiliation : <?= $Transports[3]['affiliation'] ?></p>
                <p>Soute : <?= $Transports[3]['soute'] ?></p>
            </section>
        </article>
        <article class="transports">
            <img src="https://damienguichous.sites.3wa.io/projet_starwars/ressources/images/faucon.png">
            <section class="infotransports">
                <h4><?= $Transports[4]['nom'] ?></h4>
                <p>Classe : <?= $Transports[4]['classe'] ?> </p>
                <p>Constructeur : <?= $Transports[4]['constructeur'] ?></p>
                <p>Taille : <?= $Transports[4]['taille'] ?></p>
                <p>Équipage : <?= $Transports[4]['equipage'] ?></p>
                <p>Passagers : <?= $Transports[4]['passager'] ?></p>
                <p>Affiliation : <?= $Transports[4]['affiliation'] ?></p>
                <p>Soute : <?= $Transports[4]['soute'] ?></p>
            </section>
        </article>
    </section>
</main>